<?php
require_once __DIR__ . '/WorkPepper.php';

/**
 * Implements hook_permission().
 */
function tmc_workpepper_permission() {
	return array(
			'Get workpepper data' => array(
					'title' => t('tmc_workpepper'),
			)
	);
}


/**
 * Implementation of hook_menu().
 *
 */
function tmc_workpepper_menu() {
	
	$items['workpepper-update'] = array(
			'title' => 'Workpepper Workshop Update',
			'page callback' => 'wp_workshop_update',
			'access arguments' => array('Get workpepper data'),
			'type' => MENU_CALLBACK,
	);
	
	$items['workpepper-explorer'] = array(
			'title' => 'Workpepper Data explorer',
			'page callback' => 'workpepper_explorer',
			'access arguments' => array('Get workpepper data'),
			'type' => MENU_CALLBACK,
	);
	
	return $items;
}

/*
 * Runs the updates through Cron
 */
function tmc_workpepper_cron(){
	
	$cron_interval = variable_get('tmc_workpepper_cron_interval', '3600');
	
	//get the last run time (UNIX) or now if never set
	$last_run = variable_get('tmc_workpepper_cron_last_run', REQUEST_TIME);
	//watchdog('tmc_workpepper', "last run = " . $last_run . " time now = " . REQUEST_TIME);
	
	if (REQUEST_TIME > $last_run + $cron_interval):
		wp_workshop_update();
		variable_set('tmc_workpepper_cron_last_run', REQUEST_TIME);		
	endif;		
}

/*
 * Updates Drupal workshops
 * Updates the venue code options used in locations edits
 */
function wp_workshop_update(){
	$settings['updateWorkshops'] = true;
	$settings['makeVenueCodeOptions'] = true;
	//$settings['onlyTheseCourseNids'] = array(190);
	$workPepperObj = new WorkPepper($settings);
	dsm($workPepperObj->workshopUpdates);
	$log = "<p>WP update ran</p>";
	$log .= "<p>" . implode('<br />'.PHP_EOL, $workPepperObj->log) . "</p>";
	watchdog('tmc_workpepper', $log);
	return $log;
}

/*
 * Returns the form for the WP explorer page
 */
function workpepper_explorer(){
	
	return drupal_render(drupal_get_form('workpepper_form'));
}

/*
 * Defines the form for the WP explorer page
 */
function workpepper_form($form, &$form_state) {

	$workPepper = new WorkPepper();
	//dsm($workPepper);
	
	$form['entity'] = array(
			'#type' => 'select',
			'#title' => t('Entity name'),
			'#options' => $workPepper->entityNames,
			'#description' => t('Available entity names from metadata'),
	);
	
	$form['displayOption'] = array(
			'#type' => 'select',
			'#title' => t('display'),
			'#options' => array('krumo object', 'json'),
			'#description' => t('display options'),
	);
	

	$form['submit_button'] = array(
			'#type' => 'submit',
			'#value' => t('Click Here!'),
	);

	return $form;
}

function workpepper_form_validate($form, &$form_state) {
}

function workpepper_form_submit($form, &$form_state) {
}